### ISSUE TITLE
加载动态库异常，能帮忙看一下吗？

### ISSUE THREAD

**Issue by Mrliu00070** [pqpo/SmartCropper#105]
报错的信息如下：
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/(包名)-1/base.apk"],nativeLibraryDirectories=[/data/app/(包名)-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libsmart_cropper.so"
       at java.lang.Runtime.loadLibrary(Runtime.java:367)
       at java.lang.System.loadLibrary(System.java:1076)
       at me.pqpo.smartcropperlib.SmartCropper.<clinit>(SmartCropper.java:86)
       at (包名).Application$onCreate$1.run(ProApplication.java:69)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by pqpo** [comment]
使用哪种方式依赖的？

**Comment by Mrliu00070** [comment]
不好意思，迟迟没有回复信息。
依赖：implementation 'com.github.pqpo:SmartCropper:v2.1.3'

**Comment by Mrliu00070** [comment]
请问你们能否提供下可能出现问题的地方吗？我们这边好一一排查下

**Comment by pqpo** [comment]
是否配置了 abiFilter

**Comment by Mrliu00070** [comment]
配置如下：
abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"

**Comment by pqpo** [comment]
看一下打的包里面是否有 libsmart_cropper.so

**Comment by Mrliu00070** [comment]
查看了哦，这四种ABI下都有 libsmart_cropper.so

**Comment by Mrliu00070** [comment]
请问是否能查到具体原因呢？

**Comment by bikerr** [comment]
> 请问是否能查到具体原因呢？

贴出来具体使用的环境信息 android 版本 手机型号等
