### ISSUE TITLE
application初始化裁剪，找不到动态库的问题

### ISSUE THREAD

**Issue by Mrliu00070** [pqpo/SmartCropper#110]
这是log信息，麻烦看下，非常感谢：
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file
 "/data/app/（包名）-j-XaYH4y499cuUXoxMtoPQ==/base.apk"],
nativeLibraryDirectories=[/data/app/（包名）-j-XaYH4y499cuUXoxMtoPQ==/lib/arm, /system/lib, /vendor/lib]]] couldn't find "libsmart_cropper.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at me.pqpo.smartcropperlib.SmartCropper.<clinit>(SmartCropper.java:86)
       at me.pqpo.smartcropperlib.SmartCropper.buildImageDetector(SmartCropper.java:20)
       at （包名）.ProApplication.onCreate(ProApplication.java:51)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5770)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1662)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6543)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

**Comment by liyong9** [comment]
我也想知道为什么

**Comment by liyong9** [comment]
请问你解决了吗？

**Comment by Mrliu00070** [comment]
最新版本测试好想是没有再报类似的错误了，需要再继续观察一下看看，感谢。
