### ISSUE TITLE
civShowEdgeMidPoint这个值设置为false就异常

### ISSUE THREAD

**Issue by anelka1985** [pqpo/SmartCropper#72]
自定义相机拍出的照片
保存至本地JPG格式文件
调用方法
`ivCrop.setImageToCrop(bitmap);`
时报异常
`
java.lang.NullPointerException: Attempt to get length of null array
at me.pqpo.smartcropperlib.view.CropImageView.onDrawPoints(CropImageView.java:598)
at me.pqpo.smartcropperlib.view.CropImageView.onDrawCropPoint(CropImageView.java:457)
at me.pqpo.smartcropperlib.view.CropImageView.onDraw(CropImageView.java:446)
`
可能是什么原因呢
civShowEdgeMidPoint 设置为true就好
另外这个civShowEdgeMidPoint配置是什么含义？
谢谢。

**Comment by pqpo** [comment]
Use new version by download aar file: https://github.com/pqpo/SmartCropper/releases/tag/v1.2.5
